/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEboolStruct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEboolStructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface FugaziPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "batchBuyPrice"
      | "batchExecuted"
      | "batchOrderCount"
      | "batchSellPrice"
      | "batchSize"
      | "batchStartBlock"
      | "claimOutput"
      | "currentBatch"
      | "executeBatch"
      | "getDecryptedReserves"
      | "getDecryptedShares"
      | "injectNoise"
      | "keeper"
      | "noiseInjected"
      | "outputClaimed"
      | "postBatchPrice"
      | "requestDecryptReserves"
      | "requestDecryptShares"
      | "submitOrder"
      | "token0"
      | "token1"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchExecuted"
      | "BatchPricePosted"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "NoiseInjected"
      | "OrderSubmitted"
      | "OutputClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchBuyPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchExecuted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchOrderCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSellPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "batchSize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "batchStartBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimOutput",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentBatch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "injectNoise",
    values: [InEuint128Struct]
  ): string;
  encodeFunctionData(functionFragment: "keeper", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "noiseInjected",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "outputClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "postBatchPrice",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryptReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryptShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitOrder",
    values: [InEuint128Struct, InEboolStruct]
  ): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchSize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchStartBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "injectNoise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keeper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "noiseInjected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "outputClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postBatchPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryptReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryptShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
}

export namespace BatchExecutedEvent {
  export type InputTuple = [batch: BigNumberish, orderCount: BigNumberish];
  export type OutputTuple = [batch: bigint, orderCount: bigint];
  export interface OutputObject {
    batch: bigint;
    orderCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchPricePostedEvent {
  export type InputTuple = [
    batch: BigNumberish,
    buyPrice: BigNumberish,
    sellPrice: BigNumberish
  ];
  export type OutputTuple = [
    batch: bigint,
    buyPrice: bigint,
    sellPrice: bigint
  ];
  export interface OutputObject {
    batch: bigint;
    buyPrice: bigint;
    sellPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    provider: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    provider: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NoiseInjectedEvent {
  export type InputTuple = [batch: BigNumberish];
  export type OutputTuple = [batch: bigint];
  export interface OutputObject {
    batch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSubmittedEvent {
  export type InputTuple = [
    owner: AddressLike,
    batch: BigNumberish,
    index: BigNumberish
  ];
  export type OutputTuple = [owner: string, batch: bigint, index: bigint];
  export interface OutputObject {
    owner: string;
    batch: bigint;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutputClaimedEvent {
  export type InputTuple = [user: AddressLike, batch: BigNumberish];
  export type OutputTuple = [user: string, batch: bigint];
  export interface OutputObject {
    user: string;
    batch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FugaziPool extends BaseContract {
  connect(runner?: ContractRunner | null): FugaziPool;
  waitForDeployment(): Promise<this>;

  interface: FugaziPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish],
    [void],
    "nonpayable"
  >;

  batchBuyPrice: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  batchExecuted: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  batchOrderCount: TypedContractMethod<[batch: BigNumberish], [bigint], "view">;

  batchSellPrice: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  batchSize: TypedContractMethod<[], [bigint], "view">;

  batchStartBlock: TypedContractMethod<[], [bigint], "view">;

  claimOutput: TypedContractMethod<[batch: BigNumberish], [void], "nonpayable">;

  currentBatch: TypedContractMethod<[], [bigint], "view">;

  executeBatch: TypedContractMethod<
    [batch: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDecryptedReserves: TypedContractMethod<
    [],
    [[bigint, bigint, boolean] & { r0: bigint; r1: bigint; ready: boolean }],
    "view"
  >;

  getDecryptedShares: TypedContractMethod<
    [user: AddressLike],
    [[bigint, boolean] & { shares: bigint; ready: boolean }],
    "view"
  >;

  injectNoise: TypedContractMethod<
    [encNoise: InEuint128Struct],
    [void],
    "nonpayable"
  >;

  keeper: TypedContractMethod<[], [string], "view">;

  noiseInjected: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  outputClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  postBatchPrice: TypedContractMethod<
    [batch: BigNumberish, buyPrice: BigNumberish, sellPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestDecryptReserves: TypedContractMethod<[], [void], "nonpayable">;

  requestDecryptShares: TypedContractMethod<[], [void], "nonpayable">;

  submitOrder: TypedContractMethod<
    [encAmount: InEuint128Struct, encIsBuy: InEboolStruct],
    [void],
    "nonpayable"
  >;

  token0: TypedContractMethod<[], [string], "view">;

  token1: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchBuyPrice"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchExecuted"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchOrderCount"
  ): TypedContractMethod<[batch: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchSellPrice"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchStartBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimOutput"
  ): TypedContractMethod<[batch: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentBatch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<[batch: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDecryptedReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, boolean] & { r0: bigint; r1: bigint; ready: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecryptedShares"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, boolean] & { shares: bigint; ready: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "injectNoise"
  ): TypedContractMethod<[encNoise: InEuint128Struct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "keeper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "noiseInjected"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "outputClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "postBatchPrice"
  ): TypedContractMethod<
    [batch: BigNumberish, buyPrice: BigNumberish, sellPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestDecryptReserves"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDecryptShares"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitOrder"
  ): TypedContractMethod<
    [encAmount: InEuint128Struct, encIsBuy: InEboolStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token1"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BatchExecuted"
  ): TypedContractEvent<
    BatchExecutedEvent.InputTuple,
    BatchExecutedEvent.OutputTuple,
    BatchExecutedEvent.OutputObject
  >;
  getEvent(
    key: "BatchPricePosted"
  ): TypedContractEvent<
    BatchPricePostedEvent.InputTuple,
    BatchPricePostedEvent.OutputTuple,
    BatchPricePostedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "NoiseInjected"
  ): TypedContractEvent<
    NoiseInjectedEvent.InputTuple,
    NoiseInjectedEvent.OutputTuple,
    NoiseInjectedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSubmitted"
  ): TypedContractEvent<
    OrderSubmittedEvent.InputTuple,
    OrderSubmittedEvent.OutputTuple,
    OrderSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OutputClaimed"
  ): TypedContractEvent<
    OutputClaimedEvent.InputTuple,
    OutputClaimedEvent.OutputTuple,
    OutputClaimedEvent.OutputObject
  >;

  filters: {
    "BatchExecuted(uint32,uint32)": TypedContractEvent<
      BatchExecutedEvent.InputTuple,
      BatchExecutedEvent.OutputTuple,
      BatchExecutedEvent.OutputObject
    >;
    BatchExecuted: TypedContractEvent<
      BatchExecutedEvent.InputTuple,
      BatchExecutedEvent.OutputTuple,
      BatchExecutedEvent.OutputObject
    >;

    "BatchPricePosted(uint32,uint256,uint256)": TypedContractEvent<
      BatchPricePostedEvent.InputTuple,
      BatchPricePostedEvent.OutputTuple,
      BatchPricePostedEvent.OutputObject
    >;
    BatchPricePosted: TypedContractEvent<
      BatchPricePostedEvent.InputTuple,
      BatchPricePostedEvent.OutputTuple,
      BatchPricePostedEvent.OutputObject
    >;

    "LiquidityAdded(address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(address)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "NoiseInjected(uint32)": TypedContractEvent<
      NoiseInjectedEvent.InputTuple,
      NoiseInjectedEvent.OutputTuple,
      NoiseInjectedEvent.OutputObject
    >;
    NoiseInjected: TypedContractEvent<
      NoiseInjectedEvent.InputTuple,
      NoiseInjectedEvent.OutputTuple,
      NoiseInjectedEvent.OutputObject
    >;

    "OrderSubmitted(address,uint32,uint32)": TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;
    OrderSubmitted: TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;

    "OutputClaimed(address,uint32)": TypedContractEvent<
      OutputClaimedEvent.InputTuple,
      OutputClaimedEvent.OutputTuple,
      OutputClaimedEvent.OutputObject
    >;
    OutputClaimed: TypedContractEvent<
      OutputClaimedEvent.InputTuple,
      OutputClaimedEvent.OutputTuple,
      OutputClaimedEvent.OutputObject
    >;
  };
}
